# CodeRabbit Configuration
# Netanel Systems - NASA-grade code review standards

language: en-US
early_access: false
enable_free_tier: false

reviews:
  profile: assertive
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: []
  tools:
    markdownlint:
      enabled: true
    languagetool:
      enabled: true
      level: picky
    ast-grep:
      essential_rules: true

chat:
  auto_reply: true
